version: "3"
services:
       epcis:
           container_name: epcis
           image: yaledoc/epcis2
           restart: always
           build: .
           ports:
             - "8090:8090"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo:3.6.8
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'