name: EPCIS Deployment Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Test Docker Compose
      run: |
        # Validate docker-compose.yml
        docker-compose config
        
    - name: Test deployment script
      run: |
        # Make script executable
        chmod +x deploy.sh
        
        # Test help command
        ./deploy.sh help
        
    - name: Verify environment file
      run: |
        # Check if .env file has required variables
        grep -q "EPCIS_SERVER_PORT" .env
        grep -q "MONGODB_USER" .env
        grep -q "DOCKER_NETWORK" .env
        echo "Environment file validation passed"
